### ISSUE TITLE
Kucoin integration

### ISSUE THREAD

**Issue by CodingCryptoTrading** [CodingCryptoTrading/dca-crypto-bot#2]
Someone reported problems connecting with kucoin. I don't have an account so I can't try it myself. However, reading the issues in the ccxt page I found the following:

1)	Kucoin requires a passphrase. Thus, you have to add it in the auth file (I am updating the example to include this case)
2)	You set the passphrase when you create a new API key. You should not confuse it with your trading password 
3)	An old API key may require a different logging procedure. Thus, I suggest you create a new API from scratch. 

If you still have problems, please send me the error message that you get when using the passphrase. 

If anyone has managed to get the bot to work with Kucoin, please let me know. Thank you!

**Comment by wall-X-GB** [comment]
Thank you for opening this thread again! Allow me to further explain the problem here.

I tried to use the bot in combination with the Kucoin exchange, so I edited the "auth/API_keys.yml" file to include the following:

KUCOIN:
  REAL:
    APIKEY: '123'
    SECRET: '456'
    PASSPHRASE: 'XYZ'

The API key and the secret key can be easily picked up from the API page within the Kucoin account, and as far as I understand, the "PASSPHRASE" here refers to the API passphrase Kucoin prompts you to set during the initial configuration of the API itself. However, upon initiation of the dca bot, it shows the following error:

2022-06-14 15:28:43 Program started. Initializing variables...
2022-06-14 15:28:43 Connected to KUCOIN!
2022-06-14 15:28:43 WARNING Balance checking failed: **AuthenticationError kucoin requires "password" credential**
2022-06-14 15:28:43 Summary of the investment plans: ...

The subsequent buying orders cannot be established, and its unclear to me as to how to solve this issue. 

Any help would be much appreciated!

**Comment by CodingCryptoTrading** [comment]
I found the bug. It should work now.
Would you be so kind to let me know if the purchase orders are successful? Thank you

**Comment by wall-X-GB** [comment]
Hi @CodingCryptoTrading thank you for addressing this issue! I used the updated python scripts and ran in combination with KuCoin just now. Interestingly, my first purchase went through at the specified time, but then the bot crashed and I received the following error message right afterwards:

2022-06-15 13:58:25 Next purchase: ETH (0.1-3.0 USDC) on 2022-06-15 14:00.
Time remaining: 94 s
2022-06-15 14:00:00 -> Bought 0.0 ETH at price None USDC (Cost = 0.0 USDC)
Traceback (most recent call last):
  File "dca_bot.py", line 495, in <module>
    Dca(cfg_path, api_path)
  File "dca_bot.py", line 114, in __init__
    self.buy()
  File "dca_bot.py", line 261, in buy
    plot_purchases(self.coin_to_buy, self.df_orders, self.coin[self.coin_to_buy]['PAIRING'])
  File "C:\Users\user1\Desktop\dca-crypto-bot-main\utils\stats_and_plots.py", line 9, in plot_purchases
    avg = (prices * costs).sum() / costs.sum()
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

Despite it saying "Bought 0.0 ETH at price None USDC (Cost = 0.0 USDC)", my ETH purchase was actually successful and was executed at my desired ETH price and USDC amount (which I checked in my Kucoin account), yet it seems to me there is an issue when trying to reset and get ready for the next purchase. We also experienced the same error when trying different coin pairs and varying purchase amounts.

Any help would be much appreciated!

**Comment by CodingCryptoTrading** [comment]
It is difficult to debug without a kucoin account. Anyway, I'll do my best!
It would help to read the order.json file (it might be better if you remove "orderId" and "clientOrderId"). Also, please share the orders.csv file. Both are in the "trades" folder.

**Comment by wall-X-GB** [comment]
Attached are orders.json (as orders_json.txt since it appears that Github doesn't support .json file format upload in this thread) and orders.csv files, the files include the three tries with Kucoin ETH purchases I did so far, all ended with same error. Thank you very much!

Been trying to use this bot with Kucoin since it allows lower trading amounts. Lower amounts, more frequent purchases, better DCA ✌

[orders.csv](https://github.com/CodingCryptoTrading/dca-crypto-bot/files/8907685/orders.csv)

[orders_json.txt](https://github.com/CodingCryptoTrading/dca-crypto-bot/files/8907717/orders_json.txt)

**Comment by CodingCryptoTrading** [comment]
My best guess is that the order hasn't been fulfilled yet when the status is checked.
I have updated the code so that the bot waits for a few fractions of a second before checking the status of the order.
Let me know if it works. Thank you!

**Comment by wall-X-GB** [comment]
I have tried the updated code but the same error message still remains, just wondering, is it possible to further increase the wait time until the bot check the order status? To say 2 second?

**Comment by wall-X-GB** [comment]
I tried to modify line 303 from "waiting_time = 0.25; total_time = 0" to "waiting_time = 3.00; total_time = 0", yet the error still remains, but interestingly everytime the order keeps going through without any problems on Kucoin.

**Comment by CodingCryptoTrading** [comment]
Could you please send the new json file?

**Comment by wall-X-GB** [comment]
Sure! attached are the new json and .csv orders file, and also the error message from the bot is as follows:

2022-06-16 12:21:02 -> Bought None ETH at price None USDC (Cost = None USDC)
Traceback (most recent call last):
  File "dca_bot.py", line 501, in <module>
    Dca(cfg_path, api_path)
  File "dca_bot.py", line 114, in __init__
    self.buy()
  File "dca_bot.py", line 261, in buy
    plot_purchases(self.coin_to_buy, self.df_orders, self.coin[self.coin_to_buy]['PAIRING'])
  File "C:\Users\user1\Desktop\dca-crypto-bot-main\utils\stats_and_plots.py", line 9, in plot_purchases
    avg = (prices * costs).sum() / costs.sum()
TypeError: unsupported operand type(s) for *: 'NoneType' and 'NoneType'

I have also noticed that in the previous iteration of the code the error message reads "Bought **0.0** ETH at price **None** USDC (Cost = **0.0** USDC)", but now this becomes "Bought **None** ETH at price **None** USDC (Cost = **None** USDC)", could this be some kind of number rounding problem?

Thanks a lot!

[orders.csv](https://github.com/CodingCryptoTrading/dca-crypto-bot/files/8916263/orders.csv)
[orders_json.txt](https://github.com/CodingCryptoTrading/dca-crypto-bot/files/8916265/orders_json.txt)

**Comment by CodingCryptoTrading** [comment]
I don't think so. Now many fields in the order are just null. I opened an issue in the ccxt page. Hope they can help fix this.

**Comment by wall-X-GB** [comment]
Hi @CodingCryptoTrading I have got an update, so I traced back to line 261-262 within dca_bot.py that reads 

            plot_purchases(self.coin_to_buy, self.df_orders, self.coin[self.coin_to_buy]['PAIRING'])
            self.df_stats = calculate_stats(self.coin_to_buy, self.df_orders, self.df_stats, self.stats_path)

So I commented out these two lines, ran the bot again on a "minutely" basis and it actually works! Although it still says "Bought None ETH at price None USDC (Cost = None USDC)", now the output reads the following:

Coin
ETH  2022-06-16 15:09:14.407202  minutely  0.1-0.2 USDC to 700-2500 ETH exp.

2022-06-16 15:09:14 Everything up and running!
2022-06-16 15:09:14 Next purchase: ETH (0.1-0.2 USDC) on 2022-06-16 15:09.
Time remaining: 0 s
2022-06-16 15:09:14 -> Bought None ETH at price None USDC (Cost = None USDC)
2022-06-16 15:09:14 WARNING Insufficient funds for the next ETH purchase. Top up your account!
2022-06-16 15:09:14 Next purchase: ETH (0.1-0.2 USDC) on 2022-06-16 15:10.
Time remaining: 59 s
2022-06-16 15:10:14 -> Bought None ETH at price None USDC (Cost = None USDC)
2022-06-16 15:10:14 Next purchase: ETH (0.1-0.2 USDC) on 2022-06-16 15:11.
Time remaining: 59 s
2022-06-16 15:11:14 -> Bought None ETH at price None USDC (Cost = None USDC)
2022-06-16 15:11:14 WARNING Insufficient funds for the next ETH purchase. Top up your account!
2022-06-16 15:11:14 Next purchase: ETH (0.1-0.2 USDC) on 2022-06-16 15:12.
Time remaining: 59 s
2022-06-16 15:12:14 -> Bought None ETH at price None USDC (Cost = None USDC)
2022-06-16 15:12:14 WARNING Insufficient funds for the next ETH purchase. Top up your account!
2022-06-16 15:12:14 Next purchase: ETH (0.1-0.2 USDC) on 2022-06-16 15:13.
Time remaining: 59 s
2022-06-16 15:13:14 -> Bought None ETH at price None USDC (Cost = None USDC)
2022-06-16 15:13:14 WARNING Insufficient funds for the next ETH purchase. Top up your account!
2022-06-16 15:13:14 Next purchase: ETH (0.1-0.2 USDC) on 2022-06-16 15:14.
Time remaining: 59 s
2022-06-16 15:14:14 -> Bought None ETH at price None USDC (Cost = None USDC)
2022-06-16 15:14:14 Next purchase: ETH (0.1-0.2 USDC) on 2022-06-16 15:15.
Time remaining: 59 s
2022-06-16 15:15:14 -> Bought None ETH at price None USDC (Cost = None USDC)
2022-06-16 15:15:14 WARNING Insufficient funds for the next ETH purchase. Top up your account!
2022-06-16 15:15:14 Next purchase: ETH (0.1-0.2 USDC) on 2022-06-16 15:16.

Despite all the warning messages, all individual purchases went through and were executed successfully within my desired price range. I believe the two lines that I commented out help visualise my purchase info as a matlab-like plot? Since I am doing only 0.1-0.2 USDC per order, do you think its the small amounts that are confusing the program, causing it to fail when trying to recognise my trading amounts?

**Comment by CodingCryptoTrading** [comment]
Commenting out those two lines is a sensible workaround if you don't want to receive mail notifications or get the chart. However, you are not even keeping track of your purchases which is not something good in general.

Another puzzling thing is that from time to time it doesn't find sufficient funds.

Not sure if the problem is due to the small quantities. I hope the ccxt team can shed some light on this matter

**Comment by wall-X-GB** [comment]
Thank you very much for your help! Much appreciated!

**Comment by CodingCryptoTrading** [comment]
I have updated the code. It should fix the problem with the order status (I tested it on the kucoin sandbox and it worked...I hope it will work also with real net). However, I still can't understand why you get those insufficient funds warnings from time to time.
Could you post the new log output? Thank you

**Comment by wall-X-GB** [comment]
All is fine now with the new version of the code! The log is as follows:
2022-06-24 12:13:32 Summary of the investment plans:
                  Purchase Time     Cycle                            Strategy
Coin
ETH  2022-06-24 12:13:32.032986  minutely  0.1-0.15 USDC to 700-2500 ETH exp.

2022-06-24 12:13:32 Everything up and running!
2022-06-24 12:13:32 Next purchase: ETH (0.1-0.15 USDC) on 2022-06-24 12:13.
Time remaining: 0 s
2022-06-24 12:13:32 -> Bought 0.0001172 ETH at price 1155.01 USDC (Cost = 0.135367172 USDC)
2022-06-24 12:13:33 Next purchase: ETH (0.1-0.15 USDC) on 2022-06-24 12:14.
Time remaining: 58 s
2022-06-24 12:14:32 -> Bought 0.0001172 ETH at price 1154.63 USDC (Cost = 0.135322636 USDC)
2022-06-24 12:14:32 Next purchase: ETH (0.1-0.15 USDC) on 2022-06-24 12:15.
Time remaining: 59 s
2022-06-24 12:15:32 -> Bought 0.0001172 ETH at price 1154.86 USDC (Cost = 0.135349592 USDC)
2022-06-24 12:15:32 Next purchase: ETH (0.1-0.15 USDC) on 2022-06-24 12:16.
Time remaining: 59 s
2022-06-24 12:16:32 -> Bought 0.0001172 ETH at price 1156.26 USDC (Cost = 0.135513672 USDC)
2022-06-24 12:16:32 Next purchase: ETH (0.1-0.15 USDC) on 2022-06-24 12:17.
Time remaining: 59 s
2022-06-24 12:17:32 -> Bought 0.000117 ETH at price 1156.7 USDC (Cost = 0.1353339 USDC)
2022-06-24 12:17:32 Next purchase: ETH (0.1-0.15 USDC) on 2022-06-24 12:18.
Time remaining: 59 s
2022-06-24 12:18:32 -> Bought 0.0001168 ETH at price 1157.36 USDC (Cost = 0.135179648 USDC)
2022-06-24 12:18:32 Next purchase: ETH (0.1-0.15 USDC) on 2022-06-24 12:19.
Time remaining: 59 s
2022-06-24 12:19:32 -> Bought 0.0001169 ETH at price 1156.53 USDC (Cost = 0.135198357 USDC)
2022-06-24 12:19:32 Next purchase: ETH (0.1-0.15 USDC) on 2022-06-24 12:20.
Time remaining: 59 s

It consistently shows my purchasing price and overall cost at the command prompt, and the graph under the directory "trades" is also working well now! Thanks a lot for your help!! Really useful bot!

**Comment by CodingCryptoTrading** [comment]
That's great! Glad you find it useful!
